### PR TITLE
update banners for featured projects

### LINKED ISSUE #56: add better images for featured past projects
We're hoping to feature some past projects that don't necessarily have an image of the new banner format - see the [documentation](https://ubclaunchpad.github.io/new/config/globals.html#project)

https://ubclaunchpad.github.io/new/#projects

Related: #27

### PR DESCRIPTION
**Pull request by bobheadxi**
closes #56 

* [x] inertia: https://github.com/ubclaunchpad/inertia/pull/677
* [x] rocket2: https://github.com/ubclaunchpad/rocket2/pull/452
* [x] cumulus: https://github.com/ubclaunchpad/cumulus/pull/142
* [x] minutes - dont really know what to do for this one... so I'll just leave it as is?
* [x] eat: https://github.com/ubclaunchpad/eat/pull/89
* [x] etch: https://github.com/ubclaunchpad/etch.space/pull/56
* [x] bumper: https://github.com/ubclaunchpad/bumper/pull/264 and https://github.com/ubclaunchpad/bumper/pull/265
* [x] this website! 4b72dfd

project-party

Things do now load a little slower, but I think we can resolve this with more aggressive lazy-loading - I'll open up an issue for that soon.

### CODE REVIEW

**Comment by srijonsaha** [comment]
The gifs looks amazing.

**Review by RachitMalik12 — APPROVED** [review]
Looks 😍 but I feel it getting more and more sluggish. So we should probably try to optimize before release. But great idea with the GIF banners looks so nice.

**Comment by bobheadxi** [comment]
> I feel it getting more and more sluggish

an unfortunate side effect of fancy assets 😢 will see what our lighthouse score turns out to be and if its genuinely awful will open a ticket to look into lazy-loading the project cards!

**Comment by bobheadxi** [comment]
@RachitMalik12 interestingly enough, [it seems like the score didn't really drop](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fubclaunchpad.github.io%2Fnew&tab=desktop) 🤷‍♂️ I'll keep an eye on the report every time we deploy, but for the time being I think we're in the clear

That said, [landing directly via `#projects` does have a lower score](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fubclaunchpad.github.io%2Fnew%23projects&tab=desktop), but imo not yet intolerable. In 
23451c7 I added docs recommending smaller images too

**Pull request merged**
