### PR TITLE
misc improvements to project modal styling

### LINKED ISSUE #14: project cards improvements
Right now, each project card in the Team and Projects sections only show a static image and a pretty bad placeholder title. They should:

* have good fallback behaviour for `bannerHasName: false` that looks good
* have on-hover interaction
* a simple modal on click to show the description and links (`links.repository`, `links.website`, etc.)

### PR DESCRIPTION
**Pull request by bobheadxi**
* clean up code
* round off modal corners
* use `$accent` for highlight
* adjust modal layout
* adjust animations for modal, modal background
* add modal content background

image

image

I feel like we need another color for the modal background, but none of the ones on figma look good...

### CODE REVIEW

**Comment by srijonsaha** [comment]
The modal background overlay can be more be darker to blur out the website more and pop our the modal more. I think having a light color instead of the current dark blue for the modal helps it stand out more as well, although it might go against the dark theme of the website. For content, one thing we can do is have the showcase videos for the projects in the modal and if a project doesn't have a showcase video we can fallback to the thumbnail image.

**Comment by bobheadxi** [comment]
>  For content, one thing we can do is have the showcase videos embed for the projects in the modal and if a project doesn't have a showcase video we can fallback to the thumbnail image.

https://github.com/ubclaunchpad/new/issues/75

**Comment by bobheadxi** [comment]
Imma merge this for now - let's continue iterating on this as we go!

**Review by RachitMalik12 — COMMENTED** [review]
Looks good. I like the idea of putting the showcase video in the modal. On the old website we had a more detailed description of the project (almost summary). Is there some way we can incorporate that in addition to the short description/ catchy title?  Is that what the elevator pitch refers to in #75 ?

**Pull request merged**
